server.port=${serve_port}

spring.datasource.url=${db_url}
spring.datasource.username=postgres
spring.datasource.password=${db_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.rabbitmq.addresses=${rabbit_address}
broker.queue.email.name=default.email

spring.mail.host=smtp.gmail.com
spring.mail.port=${email_port}
spring.mail.username=${email_user}
spring.mail.password=${email_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
